version: 2

multi-ecosystem-groups:
  nexdrop-dependencies:
    schedule:
      interval: weekly
      day: monday
      time: "03:00"
      timezone: Asia/Taipei
    labels: [dependencies, generated-pr, auto-merge]

updates:
  - package-ecosystem: gomod
    directory: /
    patterns: ["*"]
    multi-ecosystem-group: nexdrop-dependencies
    open-pull-requests-limit: 1
    rebase-strategy: auto
  - package-ecosystem: npm
    directory: /web
    patterns: ["*"]
    multi-ecosystem-group: nexdrop-dependencies
    open-pull-requests-limit: 1
    rebase-strategy: auto
  - package-ecosystem: npm
    directory: /extension
    patterns: ["*"]
    multi-ecosystem-group: nexdrop-dependencies
    open-pull-requests-limit: 1
    rebase-strategy: auto
  - package-ecosystem: pub
    directory: /client
    patterns: ["*"]
    multi-ecosystem-group: nexdrop-dependencies
    open-pull-requests-limit: 1
    rebase-strategy: auto
  - package-ecosystem: github-actions
    directory: /
    patterns: ["*"]
    multi-ecosystem-group: nexdrop-dependencies
    open-pull-requests-limit: 1
    rebase-strategy: auto
